filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.autodiscover:
  providers:
    # Fetch all docker container logs
    - type: docker
      hints.enabled: true
      hints.default_config.enabled: false 
      # Note: when disabled, log ingest driven by container label co.elastic.logs/enabled

processors:
  - add_docker_metadata: ~

output.logstash:
  enabled: true
  hosts: ["logstash:5044"]

http.enabled: true
http.host: 0.0.0.0

logging.metrics.enabled: false
