version: '3.8'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.7
    container_name: elasticsearch
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      # - ./elasticsearch/data:/usr/share/elasticsearch/data
    networks:
      - elastic-markov
    healthcheck:
      test: "curl -f http://localhost:9200 || exit 1"

  logstash:
    build:
      context: ./logstash
      dockerfile: Dockerfile
    image: elastic-markov-logstash
    container_name: logstash
    restart: unless-stopped
    environment:
      - "LS_JAVA_OPTS=-Xmx256m -Xms256m"
    depends_on:
      - elasticsearch
    ports:
      - "5044:5044"  # default beats
      - "9600:9600"  # web API
    networks:
      - elastic-markov
    healthcheck:
      test: "curl -f http://localhost:9600 || exit 1"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.7
    container_name: kibana
    restart: unless-stopped
    environment:
      - setup.kibana.host=kibana:5601
      - output.elasticsearch.hosts=["elasticsearch:9200"]
      - strict.perms=false
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    networks:
      - elastic-markov
    healthcheck:
      test: "curl -f http://localhost:5601 || exit 1"

  filebeat:
    build:
      context: ./filebeat
      dockerfile: Dockerfile
    image: elastic-markov-filebeat
    container_name: filebeat
    restart: unless-stopped
    depends_on:
      - elasticsearch
      - logstash
    ports:
      - "5066:5066"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    networks:
      - elastic-markov
    healthcheck:
      test: "curl -f http://localhost:5066 || exit 1"

  markov-train:
    build:
      context: ./markov/train
      dockerfile: Dockerfile
    image: elastic-markov-train
    container_name: markov-train
    restart: 'no'
    depends_on:
      - filebeat
    volumes:
      - ./markov/train/data/:/usr/src/app/data
    networks:
      - elastic-markov
    # NOTE: markov-train only runs once; exits if model+corpus already generated

  markov-gen:
    build:
      context: ./markov/gen
      dockerfile: Dockerfile
    image: elastic-markov-gen
    container_name: markov-gen
    restart: unless-stopped
    depends_on:
      - filebeat
    volumes:
      - ./markov/train/data/:/usr/src/app/data:ro
    labels:
      co.elastic.logs/enabled: true
    networks:
      - elastic-markov

networks:
  elastic-markov:
    driver: bridge
